### ISSUE TITLE
Use of deprecated numpy dtypes

### ISSUE THREAD

**Issue by landmanbester** [caracal-pipeline/crystalball#61]
* crystalball version: master
* Python version: 3.8
* Operating System: ubuntu20.02

### Description

Trying to run crystalball currently resuts in
```
crystalball -sm ~/projects/PKS1934/fitted.PKS1934.LBand.wsclean.cat.txt -o MODEL_DATA -ns 1000 -j 32 -mf 0.4 msdir/ms2_primary.ms
/home/bester/.venv/cball/lib/python3.8/site-packages/numba/core/decorators.py:262: NumbaDeprecationWarning: numba.generated_jit is deprecated. Please see the documentation at: https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-generated-jit for more information and advice on a suitable replacement.
  warnings.warn(msg, NumbaDeprecationWarning)
2023-11-07 09:20:47 | INFO     | crystalball:_predict | Crystalball version 0.4.1
2023-11-07 09:20:47 | INFO     | wsclean:import_from_wsclean | /home/bester/projects/PKS1934/fitted.PKS1934.LBand.wsclean.cat.txt contains 5153 components
2023-11-07 09:20:47 | INFO     | wsclean:import_from_wsclean | Selecting up 1000 brightest sources
2023-11-07 09:20:47 | INFO     | wsclean:import_from_wsclean | Total flux of 1000 selected components is 15.886073 Jy
Successful read/write open of default-locked table msdir/ms2_primary.ms: 25 columns, 708354 rows
Traceback (most recent call last):
  File "/home/bester/.venv/cball/bin/crystalball", line 33, in <module>
    sys.exit(load_entry_point('crystalball', 'console_scripts', 'crystalball')())
  File "/home/bester/software/crystalball/crystalball/crystalball.py", line 155, in predict
    return _predict(args)
  File "/home/bester/software/crystalball/crystalball/crystalball.py", line 191, in _predict
    args.row_chunks, args.model_chunks = get_budget(nsources,
  File "/home/bester/software/crystalball/crystalball/budget.py", line 8, in get_budget
    systmem = np.float(psutil.virtual_memory()[0])
  File "/home/bester/.venv/cball/lib/python3.8/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```
Will push a fix shortly

**Comment by landmanbester** [comment]
There were also a couple of ```np.object``` usages that I had to replace with ```object```
