### ISSUE TITLE
pip install fails with recent setuptools(?)

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/crystalball#65]
Something truly unholy happening with 0.3.0 and the latest pip stack, see below.

https://github.com/caracal-pipeline/crystalball/pull/64 might resolve this, but it would also be nice to have a workaround -- must I fall back to earlier pip/setuptools/wheel versions?

```
00:00:31 ⠸ image crystalball [0/1]: version 0.3.0 [0/2]  Downloading crystalball-0.3.0.tar.gz (15 kB)
  Preparing metadata (setup.py): started
0:00:31 ⠴ image crystalball [0/1]: version 0.3.0 [0/2]  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [26 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-irmtht1f/crystalball_0d6c1316a82242439c63d82c8870663c/setup.py", line 20, in <module>
          setup(name=PACKAGE_NAME,
        File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/usr/local/lib/python3.10/dist-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/usr/local/lib/python3.10/dist-packages/setuptools/command/egg_info.py", line 311, in run
          writer(self, ep.name, os.path.join(self.egg_info, ep.name))
        File "/usr/local/lib/python3.10/dist-packages/setuptools/command/egg_info.py", line 675, in write_pkg_info
          metadata.write_pkg_info(cmd.egg_info)
        File "/usr/local/lib/python3.10/dist-packages/setuptools/_core_metadata.py", line 134, in write_pkg_info
          self.write_pkg_file(f)
        File "/usr/local/lib/python3.10/dist-packages/setuptools/_core_metadata.py", line 175, in write_pkg_file
          write_field('License', rfc822_escape(license))
        File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/util.py", line 511, in rfc822_escape
          lines = header.split('\n')
      AttributeError: 'list' object has no attribute 'split'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
0:00:36 ⠏ image crystalball [0/1]: version 0.3.0 [0/2]error: metadata-generation-failed

```

**Comment by sjperkins** [comment]
So a `pip install .` works on master branch with the latest pip and setuptools

0.3.0 is quite [old](https://pypi.org/project/crystalball/) -- I notice there's a 0.4.1 release on github but not on pypi. I'll fix this now.

**Comment by sjperkins** [comment]
0.4.1 is now available on pypi.

**Comment by sjperkins** [comment]
> So a `pip install .` works on master branch with the latest pip and setuptools

Note this worked for me on python 3.11. I'd suggest using a recent Python interpreter to install/run crystalball, it's quite possible that the 0.3.0 version or image is invoking something like Python 3.6

**Comment by sjperkins** [comment]
0.4.2 is released on pypi https://pypi.org/project/crystalball/

I'll close this issue in anticipation of this fixing it, but please reopen if it does not.
